### ISSUE TITLE
ZFS removed when rebasing on my image

### ISSUE THREAD

**Issue by pypeaday** [ublue-os/image-template#33] opened 2024-09-29 10:38 UTC
I do not know if this is the right place to raise this issue but maybe there's a simple misunderstanding on my part.

I just recently got around to trying Aurora and was mega-pleased to see ZFS included out of the box as I use ZFS for extra storage on my desktop.

I wanted to build my own image for future customization and started with this image-template, here's the relevant part of my containerfile

```
ARG SOURCE_IMAGE="aurora"

ARG SOURCE_SUFFIX="-dx-nvidia"

ARG SOURCE_TAG="latest"

FROM ghcr.io/ublue-os/${SOURCE_IMAGE}${SOURCE_SUFFIX}:${SOURCE_TAG}
```

When I build this and rebase, I get a list of changes that will take place on reboot and one is that the zfs utils are removed.

But if I rebase again on just the stock nvidia dx aurora image then it comes back... Can someone help me with what I'm missing?

**Comment by xlionjuan** [comment] 2024-09-29 11:20
You could still add `rpm-ostree install` + that package to your `build.sh`

**Comment by pypeaday** [comment] 2024-10-08 01:45
I'm more curious why I'd have to - what's the difference in the tag and the iso?

**Comment by bsherman** [comment] 2024-10-23 05:20
> I do not know if this is the right place to raise this issue but maybe there's a simple misunderstanding on my part.

I believe a more appropriate place to ask this would be our forums ( https://universal-blue.discourse.group/ ) or in Discord ( https://discord.gg/WEu6BdFEtp ).

> ```
> ARG SOURCE_TAG="latest"
> ```
> 
> When I build this and rebase, I get a list of changes that will take place on reboot and one is that the zfs utils are removed.

The problem is Aurora (and Bluefin) only include ZFS in the `stable` tag, but you based your custom image on `latest`.

**Comment by bsherman** [comment] 2024-10-23 05:21
Closing since it's not an issue in the image-template repo itself.

**Closed by bsherman** 2024-10-23 05:21 UTC
